"""Mine INFERENCE/lexicon.py from the ANNOTATED TEACHER CORPUS.

The production lexicon must come from the data, not from someone's intuition and never from the
test set: gold-180 is excluded so the benchmark stays honest. Every term below was written by a
teacher model as a verbatim span over real IOGP / OSHA / MSHA / IADC / OISD text and survived the
schema validator.

    python -m TRAINING.build_lexicon              # regenerate INFERENCE/lexicon.py
    python -m TRAINING.build_lexicon --min 8      # stricter frequency floor
"""
from __future__ import annotations

import argparse
import collections
import json
import re
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    __package__ = "TRAINING"  # noqa: A001

from .config import DISTILLED_RAW_DIR, REPO_ROOT  # noqa: E402

OUT = REPO_ROOT / "INFERENCE" / "lexicon.py"
MINED_ROLES = ("energy_cue", "control_absent", "control_present", "control_ineffective",
               "exposure_cue", "release_cue", "no_release_cue", "outcome_cue", "pseudo_control")

# function words, pure numbers and units carry no hazard meaning on their own
_STOP = set("""a an the of in on at to for with without by from is was were are be been being and or
but not no it its this that these those he she they his her their him them we you i as if then than
when while during into over under above below near back out up down off very more most some any all
each other another such only own same so too can will just should now during per via""".split())
_HINGLISH_STOP = set("""ka ki ke ko se me mein pe par hai hain tha thi the ho hua hui gaya gayi rahe
raha rahi kiya kiye kar karke liye lekin phir bhi koi kuch aur ya nahi nahin nai bina jab tab yeh woh
uska unka apna sab ek do teen chal band khula upar neeche niche andar bahar paas dur log admi aadmi
banda samay waqt jagah wajah dauran baad pehle""".split())
_NUMLIKE = re.compile(r"^[\d.,%/\-]+$")
_UNIT = re.compile(r"^\d+(?:[.,]\d+)?\s*(m|ft|kg|ton|kv|v|bar|psi|c|mm|cm|km|l|hr|min)$", re.I)
_KEEP_MIN, _KEEP_MAX = 3, 28          # characters


def _terms(span: str) -> list[str]:
    """Content words of a span: 1- and 2-word phrases, no numbers, no function words."""
    s = re.sub(r"[^\w\s/-]", " ", span.lower()).strip()
    if not s or _NUMLIKE.match(s) or _UNIT.match(s):
        return []
    words = [w for w in s.split() if w and not _NUMLIKE.match(w)]
    keep = [w for w in words if w not in _STOP and w not in _HINGLISH_STOP and len(w) >= 3]
    out = list(keep)
    for i in range(len(words) - 1):                       # bigrams keep "gas test", "line of fire"
        bg = f"{words[i]} {words[i+1]}"
        if any(w in keep for w in (words[i], words[i + 1])) and _KEEP_MIN <= len(bg) <= _KEEP_MAX:
            out.append(bg)
    return [t for t in out if _KEEP_MIN <= len(t) <= _KEEP_MAX]


def mine(min_count: int) -> dict[str, list[tuple[str, int]]]:
    per_role: dict[str, collections.Counter] = {r: collections.Counter() for r in MINED_ROLES}
    rows = 0
    for job in ("generate", "rewind", "label"):
        p = DISTILLED_RAW_DIR / f"{job}.jsonl"
        if not p.exists():
            continue
        with open(p, "r", encoding="utf-8") as fh:
            for ln in fh:
                if not ln.strip():
                    continue
                try:
                    r = json.loads(ln)
                except json.JSONDecodeError:
                    continue
                rows += 1
                for s in r.get("spans") or []:
                    if s["role"] in per_role:
                        per_role[s["role"]].update(_terms(s.get("text") or ""))
    print(f"mined {rows} annotated rows", file=sys.stderr)
    # a term that dominates one role is a signal; a term spread evenly across roles is noise
    total = collections.Counter()
    for c in per_role.values():
        total.update(c)
    out: dict[str, list[tuple[str, int]]] = {}
    for role, c in per_role.items():
        kept = [(t, n) for t, n in c.most_common()
                if n >= min_count and n / max(1, total[t]) >= 0.55]
        out[role] = kept
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--min", type=int, default=6, help="minimum occurrences (default 6)")
    ap.add_argument("--max-terms", type=int, default=400, help="cap per role")
    a = ap.parse_args(argv)

    mined = mine(a.min)
    body = ['"""GENERATED by `python -m TRAINING.build_lexicon` - do not edit by hand.',
            "",
            "Every term is a verbatim span a teacher model wrote over real IOGP / OSHA / MSHA / IADC /",
            "OISD text that then passed the schema validator. Mined from the annotated corpus only -",
            "gold-180 is never read here, so the benchmark stays an honest held-out set.",
            '"""',
            "from __future__ import annotations", "", "import re", ""]
    counts = {}
    for role, terms in mined.items():
        terms = terms[:a.max_terms]
        counts[role] = len(terms)
        body.append(f"# {role}: {len(terms)} terms mined from the corpus")
        body.append(f"{role.upper()}_TERMS = [")
        for t, n in terms:
            body.append(f"    {t!r},  # {n}")
        body.append("]")
        body.append("")
    body += [
        "",
        "def _alt(terms: list[str]) -> str:",
        '    """Longest-first alternation so "gas test" wins over "gas"."""',
        "    esc = sorted((re.escape(t) for t in terms), key=len, reverse=True)",
        '    return r"\\b(?:" + "|".join(esc) + r")\\b" if esc else r"(?!)"',
        "",
        "",
        "MINED = {",
    ]
    for role in mined:
        body.append(f"    {role!r}: re.compile(_alt({role.upper()}_TERMS), re.I),")
    body += ["}", ""]
    OUT.write_text("\n".join(body), encoding="utf-8")
    print(json.dumps(counts, indent=2))
    print(f"-> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
