"""
Extract unlabeled rows in a copy-paste-ready block, for labeling in ANY chatbot
(ChatGPT, Claude, Gemini, ...) - no API key, no agent, no rate limit.

    python -m TRAINING.extract_for_labeling                 # next 40 rows -> DATA/distilled/manual/rows_to_label.md
    python -m TRAINING.extract_for_labeling --limit 100     # bigger chunk
    python -m TRAINING.extract_for_labeling --force         # include rows already labelled

Rows already present in DATA/distilled/raw/label.jsonl are skipped, so running it again
always gives you the NEXT chunk.  Paste TRAINING/label_prompt.md first, then this file's
ROWS section, into the chatbot; save its JSON reply and run:

    python -m TRAINING.import_labeled_answers <reply.json>
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    __package__ = "TRAINING"  # noqa: A001

from .config import DISTILLED_DIR, DISTILLED_RAW_DIR, PROMPT_VERSION, TEACHER_INPUT  # noqa: E402
from .distill.prompts import label_messages  # noqa: E402

MANUAL_DIR = DISTILLED_DIR / "manual"
DEFAULT_OUT = MANUAL_DIR / "rows_to_label.md"
PROMPT_FILE = Path(__file__).resolve().parent / "label_prompt.md"


def labelled_ids() -> set[str]:
    """input_ids that already have an accepted row (any teacher, API or manual)."""
    done: set[str] = set()
    p = DISTILLED_RAW_DIR / "label.jsonl"
    if p.exists():
        with open(p, "r", encoding="utf-8") as fh:
            for ln in fh:
                if not ln.strip():
                    continue
                try:
                    r = json.loads(ln)
                except json.JSONDecodeError:
                    continue
                for k in ("seed_id", "input_id"):
                    if r.get(k):
                        done.add(r[k])
    return done


def pending(limit: int | None, force: bool = False) -> list[dict]:
    if not TEACHER_INPUT.exists():
        raise SystemExit(f"missing {TEACHER_INPUT} - run `python -m CLEANING.run_pipeline` first")
    done = set() if force else labelled_ids()
    rows = []
    with open(TEACHER_INPUT, "r", encoding="utf-8") as fh:
        for ln in fh:
            if not ln.strip():
                continue
            r = json.loads(ln)
            if r.get("teacher_prompt") != "label" or r["input_id"] in done:
                continue
            rows.append(r)
    rows.sort(key=lambda r: (0 if r["source"] == "osha_sir" else 1, r["input_id"]))  # oil & gas before mining
    return rows[:limit] if limit else rows


def _readable(block: str) -> str:
    """The API lanes send the ROWS array as one compact line - fine for a socket, unreadable when a
    human has to paste and eyeball it. Re-emit the same array with one row per line."""
    i, j = block.find("["), block.rfind("]")
    if i < 0 or j < i:
        return block
    try:
        rows = json.loads(block[i:j + 1])
    except json.JSONDecodeError:
        return block
    body = ",\n".join("  " + json.dumps(r, ensure_ascii=False) for r in rows)
    return f"{block[:i]}[\n{body}\n]{block[j + 1:]}"


def render(rows: list[dict]) -> tuple[str, str]:
    """(system prompt, rows block) - built by the SAME code the API teachers use, so a chatbot
    answering this produces rows the validator treats identically."""
    msgs = label_messages(rows)
    return msgs[0]["content"], _readable(msgs[1]["content"])


def write_prompt_file(system: str) -> bool:
    """Keep TRAINING/label_prompt.md in sync with the pipeline. True if it changed."""
    body = (f"<!-- generated by TRAINING/extract_for_labeling.py | {PROMPT_VERSION} - do not edit by hand -->\n"
            f"# Label prompt (paste this FIRST, once per chat)\n\n{system}\n")
    if PROMPT_FILE.exists() and PROMPT_FILE.read_text(encoding="utf-8") == body:
        return False
    PROMPT_FILE.write_text(body, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="extract rows for manual labelling in any chatbot")
    ap.add_argument("--output", default=str(DEFAULT_OUT), help=f"output file (default {DEFAULT_OUT})")
    ap.add_argument("--limit", type=int, default=40, help="how many rows (default 40 - a comfortable chatbot chunk)")
    ap.add_argument("--force", action="store_true", help="include rows that are already labelled")
    a = ap.parse_args(argv)

    rows = pending(a.limit, a.force)
    if not rows:
        print("NOTHING LEFT: every label row already has an accepted annotation.")
        return 0

    remaining = len(pending(None, a.force))
    system, block = render(rows)
    changed = write_prompt_file(system)

    header = (f"<!-- {len(rows)} rows | {PROMPT_VERSION} -->\n"
              f"# ROWS TO LABEL\n\n"
              f"Paste `TRAINING/label_prompt.md` into the chat FIRST (once per chat), then paste\n"
              f"everything below the line. Save the JSON reply to a file and import it with\n"
              f"`python -m TRAINING.import_labeled_answers <file>` - never paste it into label.jsonl\n"
              f"by hand, or the rows skip validation and arrive without spans/offsets.\n\n"
              f"Most common reject: a span longer than 12 words. Copy the SHORTEST verbatim phrase\n"
              f"that carries the meaning, not the whole clause.\n\n---\n\n")
    if a.output == "-":
        sys.stdout.write(header + block + "\n")
    else:
        out = Path(a.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(header + block + "\n", encoding="utf-8")
        print(f"{len(rows)} rows -> {out}")
    print(f"prompt      -> {PROMPT_FILE}" + ("  (UPDATED - paste it again in a fresh chat)" if changed else "  (unchanged)"))
    print(f"{remaining - len(rows)} label rows still unlabelled after this chunk")
    print("then: python -m TRAINING.import_labeled_answers <reply.json>")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
