"""GENERATED by `python -m TRAINING.build_lexicon` - do not edit by hand.

Every term is a verbatim span a teacher model wrote over real IOGP / OSHA / MSHA / IADC /
OISD text that then passed the schema validator. Mined from the annotated corpus only -
gold-180 is never read here, so the benchmark stays an honest held-out set.
"""
from __future__ import annotations

import re

# energy_cue: 400 terms mined from the corpus
ENERGY_CUE_TERMS = [
    'heavy',  # 1362
    'line',  # 1315
    'equipment',  # 1277
    'heavy equipment',  # 1181
    'pressure',  # 811
    'pipe',  # 723
    'feet',  # 473
    'kv line',  # 448
    'load',  # 436
    'high',  # 406
    'height',  # 401
    'drill',  # 382
    'welding',  # 339
    'hose',  # 338
    'h2s',  # 315
    'crane',  # 309
    'elevator',  # 297
    'cable',  # 295
    'high pressure',  # 289
    'm height',  # 256
    'set',  # 227
    'pressurized',  # 226
    'ton',  # 224
    'pressure line',  # 224
    'kg elevator',  # 222
    'hyva',  # 216
    'tipper',  # 215
    'hyva tipper',  # 211
    'panel',  # 201
    'block',  # 191
    'welding set',  # 189
    'wire',  # 189
    'ऊपर',  # 188
    'pallet',  # 177
    'spanner',  # 171
    'collar',  # 169
    'driver',  # 165
    'drill collar',  # 158
    'wooden pallet',  # 158
    'power',  # 155
    'kelly',  # 154
    'compressor',  # 150
    'ऊपर स',  # 148
    'टर ऊपर',  # 147
    'truck',  # 145
    'hydra',  # 145
    'battery',  # 144
    'low',  # 143
    'suspended',  # 142
    'cardboard',  # 140
    'sheet',  # 140
    'cardboard sheet',  # 140
    'winch',  # 140
    'forklift',  # 138
    'screw',  # 137
    'pipe ka',  # 136
    'telephone',  # 136
    'telephone wire',  # 136
    'pressure hose',  # 135
    'low pressure',  # 134
    'hydra crane',  # 133
    'tapping',  # 132
    'tukda',  # 131
    'screw driver',  # 131
    'plastic',  # 131
    'ka tukda',  # 130
    'hot tapping',  # 129
    'plastic pipe',  # 128
    'oil',  # 126
    'terminal',  # 126
    'v battery',  # 125
    'casing',  # 123
    'battery terminal',  # 123
    'crude',  # 120
    'ka spanner',  # 119
    'live',  # 116
    'leak',  # 116
    'rotating',  # 115
    'spill',  # 115
    'grease',  # 113
    'steam',  # 112
    'drill pipe',  # 112
    'roof',  # 107
    'grease spill',  # 107
    'pressurized hose',  # 106
    'lift',  # 103
    'meters',  # 100
    'tong',  # 98
    'bar',  # 97
    'meter',  # 96
    'hydraulic',  # 93
    'water',  # 89
    'well',  # 89
    'tapping machine',  # 88
    'overhead',  # 88
    'tank roof',  # 87
    'boom',  # 87
    'kv panel',  # 85
    'die',  # 85
    'air',  # 83
    'pipeline',  # 79
    'bop',  # 75
    'separator',  # 75
    'pulley',  # 75
    'inch',  # 74
    'tongs',  # 74
    'power line',  # 74
    'cutting',  # 73
    'box',  # 73
    'circuit',  # 73
    'winch cable',  # 73
    'h2s gas',  # 71
    'mcc',  # 70
    'hoist',  # 69
    'traveling',  # 69
    'cylinder',  # 68
    'kg die',  # 68
    'mcc panel',  # 66
    'suspended load',  # 66
    'joint',  # 66
    'traveling block',  # 66
    'unit',  # 64
    'flange',  # 64
    'mast',  # 64
    'energised',  # 63
    'tubing',  # 63
    'tension',  # 63
    'drive',  # 62
    'kelly bar',  # 61
    'deep',  # 61
    'pole',  # 61
    'jack',  # 61
    'feet upar',  # 60
    'wrench',  # 59
    'string',  # 59
    'overhead power',  # 59
    'bucket',  # 58
    'psi',  # 58
    'engine',  # 58
    'running',  # 57
    'level',  # 57
    'scaffold',  # 57
    'steel',  # 57
    'electrical',  # 55
    'assembly',  # 55
    'pulley block',  # 54
    'chain pulley',  # 53
    'helicopter',  # 53
    'shaft',  # 53
    'top drive',  # 52
    'motor',  # 51
    'chemical',  # 50
    'high-pressure',  # 50
    'g hand',  # 50
    'hand spanner',  # 50
    'ton ka',  # 49
    'gas compressor',  # 49
    'crude tank',  # 48
    'spool',  # 48
    'metal',  # 48
    'vehicle',  # 46
    'scaffolding',  # 46
    'grinder',  # 46
    'nitrogen',  # 46
    'v control',  # 46
    'control circuit',  # 46
    'energized',  # 45
    'kv cable',  # 45
    'table',  # 45
    'db box',  # 44
    'crude oil',  # 44
    'torch',  # 43
    'vessel',  # 43
    'drum',  # 42
    'die m',  # 42
    'ton load',  # 42
    'bolero',  # 42
    'chalu',  # 41
    'tonne',  # 41
    'moving',  # 41
    'hydrocarbon',  # 39
    'steam line',  # 39
    'blocks',  # 39
    'container',  # 39
    'flammable',  # 38
    'walkway',  # 38
    'diesel',  # 37
    'operation',  # 37
    'line ka',  # 37
    'section',  # 37
    'vapors',  # 37
    'stack',  # 36
    'ton pipe',  # 36
    'fuel',  # 36
    'lines',  # 36
    'detector alarm',  # 35
    'electric',  # 35
    'lightning',  # 35
    'metres',  # 35
    'kg drill',  # 34
    'utha',  # 34
    'hoisting',  # 34
    'pumping',  # 34
    'loaded',  # 33
    'conveyor',  # 33
    'h2s detector',  # 33
    'lpg',  # 33
    'gas leak',  # 33
    'crane ka',  # 32
    'ka load',  # 32
    'plate',  # 32
    'rotary',  # 32
    'floorot',  # 32
    'flat',  # 32
    'flat ground',  # 32
    'lel',  # 31
    'mud pump',  # 31
    'oxygen',  # 31
    'tire',  # 31
    'uthaya',  # 31
    'gas cutting',  # 30
    'storage',  # 30
    'grinding',  # 30
    'kg pipe',  # 30
    'hammer',  # 30
    'blind flange',  # 30
    'fan',  # 29
    'excavation',  # 29
    'fluid',  # 29
    'rotary table',  # 29
    'under pressure',  # 29
    'flowline',  # 28
    'kv mcc',  # 28
    'cutting set',  # 28
    'gangway',  # 28
    'counterweight',  # 28
    'lbs',  # 28
    'crane se',  # 27
    'tanker',  # 27
    'burner',  # 27
    'drill string',  # 27
    'natural',  # 27
    'trolley',  # 26
    'generator',  # 26
    'm deep',  # 26
    'plant',  # 26
    'gas line',  # 26
    'tractor',  # 26
    'gun',  # 26
    'natural gas',  # 26
    'drawworks',  # 25
    'monsoon',  # 25
    'hanging',  # 25
    'beam',  # 25
    'fold-up',  # 25
    'fold-up walkway',  # 25
    'cloud',  # 25
    'ka boom',  # 24
    'c steam',  # 24
    'ka pipe',  # 24
    'tirfor',  # 24
    'ppm',  # 24
    'cathead',  # 24
    'elevators',  # 24
    'counterweights',  # 24
    'chemical container',  # 24
    'h2s alarm',  # 23
    'kg load',  # 23
    'loader',  # 23
    'sand',  # 23
    'pumping unit',  # 23
    'storage tank',  # 22
    'excavator',  # 22
    'leak ho',  # 22
    'exhaust',  # 22
    'propane',  # 22
    'hot water',  # 22
    'longline',  # 22
    'helicopter longline',  # 22
    'meter height',  # 21
    'crane boom',  # 21
    'scafolding',  # 21
    'press',  # 21
    'hydrogen',  # 21
    'wet floor',  # 21
    'iron',  # 21
    'gas cloud',  # 21
    'condensate',  # 21
    'travelling',  # 21
    'h2s leak',  # 20
    'poclain',  # 20
    'set chalu',  # 20
    'reading',  # 20
    'rack',  # 20
    'volt',  # 20
    'voltage',  # 20
    'heat',  # 20
    'tds',  # 20
    'plug',  # 20
    'power lines',  # 20
    'hydrocarbon gas',  # 20
    'time',  # 19
    'bop stack',  # 19
    'tyre',  # 19
    'tree',  # 19
    'wire rope',  # 19
    'cart',  # 19
    'volts',  # 19
    'drill line',  # 19
    'bushing',  # 18
    'bundle',  # 18
    'inches',  # 18
    'lifted',  # 18
    'level floor',  # 18
    'pounds',  # 18
    'petroleum',  # 18
    'bowser',  # 17
    'concrete',  # 17
    'tray',  # 17
    'cable tray',  # 17
    'pipe wrench',  # 17
    'boiler',  # 17
    'uthate',  # 17
    'feeder',  # 17
    'set on',  # 17
    'liquid',  # 17
    'power tong',  # 17
    '7200-volt',  # 17
    'travelling block',  # 17
    'crude line',  # 16
    'pipes',  # 16
    'se pipe',  # 16
    'sharp',  # 16
    'steam pipe',  # 16
    'loaded casing',  # 16
    'line energised',  # 16
    'extension',  # 16
    'pickup',  # 16
    'circuit breaker',  # 16
    'hydraulic jack',  # 16
    'sub',  # 16
    'powered',  # 16
    'vibrating',  # 16
    'heater',  # 16
    'underground',  # 16
    'tugger',  # 16
    'cutting torch',  # 16
    'spinner',  # 16
    'degrees',  # 16
    'flammable vapors',  # 16
    'pressurized spool',  # 16
    'burner plug',  # 16
    'crane load',  # 15
    'heavy drill',  # 15
    'collar m',  # 15
    'supply',  # 15
    'height se',  # 15
    'meter upar',  # 15
    'psi pressure',  # 15
    'driving',  # 15
    'high speed',  # 15
    'kelly bushing',  # 15
    'welding ka',  # 15
    'electrical cable',  # 15
    'tower',  # 15
    'lifting a',  # 15
    'lowering',  # 15
    'rotating shaft',  # 15
    'air winch',  # 15
    'plates',  # 15
    'riser',  # 15
    'pallet jack',  # 15
    'air hoist',  # 15
    'vacuum',  # 15
    'machinery',  # 14
    'latka',  # 14
    'long',  # 14
    'tipper loaded',  # 14
    'discharge',  # 14
    'saw',  # 14
    'scba cylinder',  # 14
    'utha raha',  # 14
    'feet height',  # 14
    'filter',  # 14
    'sand separator',  # 14
    'roughneck',  # 14
    'iron roughneck',  # 14
    'frac',  # 14
    'pump jack',  # 14
    'driver ne',  # 13
    'of drill',  # 13
    '5m height',  # 13
    'kg wrench',  # 13
    'cellar pit',  # 13
    'set ka',  # 13
    'load m',  # 13
    'recovery',  # 13
    'excavator bucket',  # 13
    'm ऊपर',  # 13
    'rotate',  # 13
]

# control_absent: 400 terms mined from the corpus
CONTROL_ABSENT_TERMS = [
    'loto',  # 928
    'test',  # 647
    'barricade',  # 638
    'permit',  # 616
    'gas test',  # 581
    'isolation',  # 546
    'harness',  # 468
    'safety',  # 449
    'ptw',  # 436
    'kora',  # 421
    'fall',  # 401
    'guard',  # 390
    'plan',  # 378
    'check',  # 375
    'work',  # 329
    'missing',  # 324
    'lifting',  # 322
    'scba',  # 309
    'lifting plan',  # 298
    'work permit',  # 286
    'arrest',  # 285
    'fall arrest',  # 282
    'loto nahi',  # 277
    'hot work',  # 275
    'barricade nahi',  # 239
    'nohol',  # 227
    'bina harness',  # 221
    'kora nai',  # 216
    'proper',  # 187
    'system',  # 182
    'lanyard',  # 182
    'tag',  # 181
    'nasil',  # 174
    'jsa',  # 170
    'protection',  # 170
    'check nahi',  # 166
    'barrier',  # 164
    'harness ke',  # 163
    'koi barricade',  # 153
    'drop',  # 147
    'test nahi',  # 147
    'drop zone',  # 146
    'entry',  # 145
    'no exclusion',  # 132
    'zone barricade',  # 128
    'secondary',  # 127
    'entry permit',  # 126
    'verify',  # 126
    'arrest system',  # 122
    'bina loto',  # 122
    'bina ptw',  # 117
    'kisi',  # 115
    'kora nohol',  # 114
    'lagaya',  # 114
    'fall protection',  # 112
    'bina gas',  # 111
    'bypass',  # 111
    'gas detector',  # 105
    'inspection',  # 103
    'bina kisi',  # 103
    'nahi lagaya',  # 102
    'lock',  # 100
    'spotter',  # 96
    'watch',  # 95
    'done',  # 94
    'no gas',  # 93
    'fire watch',  # 93
    'isolation nahi',  # 91
    'permit ke',  # 90
    'verifying',  # 84
    'ptw ke',  # 84
    'guard nahi',  # 83
    'without verifying',  # 83
    'tag line',  # 83
    'no loto',  # 83
    'zone nahi',  # 80
    'loto ke',  # 79
    'परव',  # 78
    'स परव',  # 78
    'परव जन',  # 78
    'यवस',  # 78
    'अव यवस',  # 78
    'यवस थ',  # 78
    'verify nahi',  # 77
    'no barricade',  # 77
    'support',  # 76
    'housekeeping',  # 75
    'secured',  # 74
    'koi safety',  # 73
    'logging',  # 73
    'thik nohol',  # 73
    'isolated',  # 72
    'any fall',  # 72
    'logging thik',  # 72
    'verification',  # 70
    'no fall',  # 70
    'check kiye',  # 69
    'machine guard',  # 68
    'retention',  # 68
    'plan nahi',  # 67
    'communication',  # 66
    'permit nahi',  # 65
    'without harness',  # 65
    'bina fall',  # 65
    'guard missing',  # 64
    'barrier nahi',  # 64
    'bypassed',  # 64
    'loto नह',  # 64
    'details',  # 64
    'submit',  # 64
    'details submit',  # 64
    'submit kora',  # 64
    'secondary retention',  # 64
    'test ke',  # 63
    'bina hot',  # 63
    'lanyard nahi',  # 62
    'without loto',  # 62
    'has',  # 62
    'pin',  # 61
    'loto verify',  # 61
    'valid',  # 59
    'check kora',  # 58
    'bina barricade',  # 58
    'checking',  # 58
    'without proper',  # 57
    'using',  # 57
    'tool lanyard',  # 56
    'koi exclusion',  # 56
    'missing tha',  # 55
    'warning',  # 55
    'physical',  # 55
    'mechanical',  # 55
    'nahi pehna',  # 54
    'properly',  # 54
    'barricade ke',  # 54
    'no lifting',  # 53
    'bina scba',  # 52
    'scba ke',  # 52
    'barricading',  # 52
    'bina safety',  # 52
    'secure',  # 51
    'bhal',  # 51
    'उसक',  # 51
    'ह उसक',  # 51
    'उसक प',  # 51
    'a valid',  # 50
    'no isolation',  # 49
    'used',  # 49
    'a hot',  # 49
    'bhal nasil',  # 49
    'koi lanyard',  # 48
    'housekeeping bhal',  # 48
    'without gas',  # 47
    'scba bina',  # 47
    'without checking',  # 47
    'procedure',  # 46
    'kono',  # 46
    'latch',  # 45
    'not secured',  # 45
    'bina ppe',  # 44
    'nahi laga',  # 44
    'hata',  # 44
    'koi guard',  # 44
    'no secondary',  # 44
    'not isolated',  # 43
    'koi loto',  # 43
    'present',  # 43
    'barricaded',  # 42
    'is missing',  # 42
    'guardrail',  # 41
    'not done',  # 41
    'bypassed the',  # 40
    'ptw nahi',  # 40
    'harness nahi',  # 39
    'removed',  # 39
    'sign',  # 39
    'performed',  # 39
    'test kora',  # 39
    'koi fall',  # 38
    'formal',  # 38
    'lacks',  # 38
    'laga nasil',  # 38
    'safety belt',  # 37
    'isolation verify',  # 37
    'without ptw',  # 37
    'a lifting',  # 37
    'safety barrier',  # 37
    'not verified',  # 37
    'kora nasil',  # 37
    'device',  # 37
    'barricading nahi',  # 37
    'bina tag',  # 36
    'lanyard ke',  # 36
    'bina proper',  # 36
    'barricades',  # 36
    'testing',  # 35
    'horn',  # 35
    'lagaya gaya',  # 35
    'guarding',  # 35
    'no drop',  # 35
    'hwp',  # 34
    'barricade nai',  # 34
    'clear',  # 34
    'any exclusion',  # 34
    'not barricaded',  # 33
    'lock nahi',  # 33
    'not properly',  # 33
    'bypass kar',  # 33
    'koi isolation',  # 32
    'has been',  # 32
    'koi lifting',  # 32
    'bina jsa',  # 31
    'follow',  # 31
    'control nahi',  # 31
    'without fall',  # 31
    'bina lifting',  # 31
    'did',  # 30
    'did not',  # 30
    'net',  # 30
    'koi drop',  # 30
    'ppe ke',  # 29
    'signal',  # 29
    'ventilation',  # 29
    'koi barrier',  # 29
    'nahi liya',  # 29
    'koi gas',  # 29
    'lockout',  # 29
    'a harness',  # 29
    'has not',  # 29
    'specific',  # 29
    'restraint',  # 29
    'scba check',  # 28
    'absent',  # 28
    'no fire',  # 28
    'applied',  # 28
    'without using',  # 28
    'physical barrier',  # 28
    'safety harness',  # 27
    'earthing',  # 27
    'bypass karke',  # 27
    'hata diya',  # 27
    'test aur',  # 27
    'issued',  # 27
    'not wearing',  # 27
    'inspection nahi',  # 27
    'isolation check',  # 26
    'aur gas',  # 26
    'arrest ke',  # 26
    'test not',  # 26
    'no hot',  # 26
    'a proper',  # 26
    'assessment',  # 26
    'no physical',  # 26
    'securing',  # 26
    'zone nai',  # 26
    'scba nahi',  # 25
    'safety net',  # 25
    'available',  # 25
    'no permit',  # 25
    'signage',  # 25
    'loto kora',  # 25
    'grounding',  # 25
    'locking',  # 25
    'a ptw',  # 24
    'tagline',  # 24
    'without isolation',  # 24
    'established',  # 24
    'any drop',  # 24
    'plan ke',  # 24
    'installed',  # 24
    'clearance',  # 24
    'operational',  # 24
    'lift plan',  # 23
    'a gas',  # 23
    'आइस',  # 23
    'आइस ल',  # 23
    'test done',  # 23
    'a safety',  # 23
    'loto verification',  # 23
    'no ptw',  # 23
    'fully',  # 23
    'koi barricading',  # 23
    'test bhi',  # 22
    'missing hai',  # 22
    'gas testing',  # 22
    'परम',  # 22
    'परम ट',  # 22
    'escort',  # 22
    'no safety',  # 22
    'was missing',  # 22
    'पहन',  # 22
    'verifying isolation',  # 22
    'without hot',  # 22
    'the required',  # 22
    'permit nohol',  # 22
    'cage',  # 22
    'verifying the',  # 21
    'bina exclusion',  # 21
    'lock out',  # 21
    'marked',  # 21
    'place',  # 21
    'guard rail',  # 21
    'esd',  # 21
    'ptw aur',  # 21
    'bina lanyard',  # 21
    'no spotter',  # 21
    'lacked',  # 21
    'not using',  # 21
    'permit nai',  # 21
    'general',  # 21
    'gaps',  # 21
    'general communication',  # 21
    'communication gaps',  # 21
    'ई loto',  # 21
    'been verified',  # 21
    'no mechanical',  # 21
    'insulation',  # 20
    'follow nahi',  # 20
    'jsa ke',  # 20
    'guard ke',  # 20
    'no tag',  # 20
    'in place',  # 20
    'arrest nahi',  # 20
    'नह पहन',  # 20
    'report',  # 20
    'bina isolation',  # 20
    'no machine',  # 20
    'distance',  # 20
    'no jsa',  # 20
    'without performing',  # 20
    'noted',  # 20
    'harness laga',  # 20
    'plan nai',  # 20
    'bina check',  # 19
    'safety guard',  # 19
    'shoring',  # 19
    'without escort',  # 19
    'use nahi',  # 19
    'hoy',  # 19
    'kora hoy',  # 19
    'hoy ni',  # 19
    'bina guard',  # 19
    'watch ke',  # 19
    'using a',  # 19
    'न loto',  # 19
    'remarks',  # 19
    'lacked specific',  # 19
    'specific operational',  # 19
    'operational remarks',  # 19
    'substandard',  # 19
    'housekeeping was',  # 19
    'was noted',  # 19
    'noted to',  # 19
    'be substandard',  # 19
    'designated',  # 19
    'backup',  # 19
    'test was',  # 18
    'permit or',  # 18
    'zone ke',  # 18
    'bypassing',  # 18
    'no guard',  # 18
    'line nahi',  # 18
    'management',  # 18
    'test kiye',  # 18
    'verify kora',  # 18
    'or gas',  # 18
    'training',  # 18
    'label',  # 18
    'parking',  # 17
    'valid ptw',  # 17
    'safety latch',  # 17
    'loto kiye',  # 17
    'toe',  # 17
    'bina fire',  # 17
    'bina tool',  # 17
    'tag out',  # 17
    'or loto',  # 17
    'shield',  # 17
    'a spotter',  # 17
    'approved',  # 17
    'or exclusion',  # 17
    'authorization',  # 17
    'secure nahi',  # 17
    'any physical',  # 17
    'not fully',  # 17
    'spotter nahi',  # 17
    'a verified',  # 17
    'no formal',  # 17
    'koi secondary',  # 17
    'interlock',  # 16
    'without wearing',  # 16
    'isolation tag',  # 16
    'watcher',  # 16
    'bina lock',  # 16
    'bina entry',  # 16
    'any loto',  # 16
    'tape',  # 16
    'isolation ke',  # 16
    'loto क',  # 16
    'ptw bina',  # 16
]

# control_present: 44 terms mined from the corpus. Six were removed by hand on 2026-09-13:
# 'the worker', 'न worker', 'worker क', 'protected the', 'verified tha', 'was verified' - the
# miner saw "the worker was protected" and learned the PERSON as the barrier. That single entry
# turned "pressure released ... half burn to the worker" into CAPACITY (barrier limited the harm).
CONTROL_PRESENT_TERMS = [
    'zone',  # 1759
    'exclusion',  # 1753
    'exclusion zone',  # 1752
    'verified',  # 585
    'zone verified',  # 495
    'protected',  # 408
    'zone protected',  # 376
    'zone न',  # 371
    'thik',  # 276
    'thik asil',  # 274
    'energy',  # 252
    'energy isolation',  # 251
    'isolation loto',  # 249
    'zone thik',  # 246
    'elcb',  # 147
    'elcb ट',  # 144
    'प-ज',  # 143
    'र प-ज',  # 143
    'प-ज न',  # 143
    'test monitoring',  # 40
    'loto verified',  # 31
    'drop-zone',  # 28
    'drop-zone barricade',  # 28
    'permit ptw',  # 22
    'loto न',  # 16
    'verify kiya',  # 14
    'monitoring verified',  # 13
    'loto protected',  # 12
    'turant',  # 11
    'rok',  # 11
    'bhalke',  # 11
    'barricade न',  # 11
    'loto thik',  # 10
    'monitoring न',  # 10
    'arrest engaged',  # 9
    'lock laga',  # 9
    'kora asil',  # 9
    'kar liya',  # 8
    'ptw verified',  # 8
    'ne turant',  # 7
    'monitoring protected',  # 7
    'barricade verified',  # 7
    'rok liya',  # 6
    'ptw protected',  # 6
]

# control_ineffective: 24 terms mined from the corpus
CONTROL_INEFFECTIVE_TERMS = [
    'clip',  # 36
    'lifeline',  # 35
    'anchor point',  # 22
    'clip nahi',  # 21
    'clipped',  # 17
    'lanyard was',  # 16
    'to lifeline',  # 15
    'hooked',  # 14
    'not hooked',  # 13
    'hooked to',  # 13
    'anchored',  # 12
    'not clipped',  # 10
    'hook nahi',  # 10
    'clipped to',  # 9
    'not anchored',  # 7
    'the lifeline',  # 7
    'connect nahi',  # 7
    'isolation not',  # 7
    'lanyard to',  # 7
    'point se',  # 6
    'se connect',  # 6
    'correctly',  # 6
    'appears',  # 6
    'lanyard hook',  # 6
]

# exposure_cue: 400 terms mined from the corpus
EXPOSURE_CUE_TERMS = [
    'worker',  # 2377
    'helper',  # 1314
    'khada',  # 878
    'safe',  # 820
    'worker safe',  # 817
    'standing',  # 677
    'kaam',  # 612
    'safe tha',  # 544
    'employee',  # 497
    'operator',  # 485
    'khada tha',  # 476
    'kaam kar',  # 439
    'roustabout',  # 379
    'line of',  # 316
    'directly',  # 299
    'of fire',  # 297
    'crew',  # 290
    'safe asil',  # 272
    'neeche khada',  # 270
    'khada hai',  # 250
    'ase',  # 238
    'working',  # 238
    'area',  # 234
    'khade',  # 227
    'inside',  # 209
    'neeche roustabout',  # 202
    'technician',  # 200
    'derrickman',  # 183
    'standing directly',  # 163
    'rig',  # 156
    'contractor',  # 148
    'neeche helper',  # 148
    'staff',  # 146
    'underneath',  # 145
    'standing near',  # 139
    'between',  # 139
    'bhitorot',  # 136
    'workers',  # 132
    'the line',  # 116
    'person',  # 111
    'station',  # 107
    'inside the',  # 107
    'mistri',  # 104
    'helper khada',  # 100
    'road',  # 100
    'walking',  # 97
    'rig floor',  # 95
    'khade the',  # 94
    'fire mein',  # 91
    'khade hain',  # 91
    'between the',  # 91
    'standing on',  # 87
    'manuh',  # 83
    'directly in',  # 82
    'positioned',  # 81
    'driller',  # 80
    'mud pit',  # 77
    'standing in',  # 75
    'roustabout kaam',  # 74
    'directly underneath',  # 74
    'मजद',  # 72
    'मजद र',  # 72
    'korise',  # 72
    'workshopot',  # 72
    'haath',  # 71
    'house',  # 67
    'nearby',  # 66
    'board pe',  # 66
    'helper neeche',  # 66
    'employee s',  # 66
    'labour',  # 65
    'paas khada',  # 64
    'areaot',  # 64
    'station areaot',  # 64
    'roustabout khada',  # 63
    'neeche khade',  # 62
    'personnel',  # 62
    'floorman',  # 61
    'kori',  # 59
    'team',  # 58
    'pump house',  # 58
    'directly under',  # 56
    'ऑपर',  # 56
    'ऑपर टर',  # 56
    'was standing',  # 56
    'ggs',  # 55
    'close',  # 55
    'kaam korise',  # 55
    'kori ase',  # 55
    'row',  # 54
    'rigger',  # 54
    'neeche kaam',  # 52
    'climbing',  # 51
    'the load',  # 51
    'working on',  # 50
    'deck',  # 50
    'ggs pump',  # 50
    'pump area',  # 49
    'ek helper',  # 48
    'wahan',  # 47
    'entered',  # 46
    'ocs',  # 46
    'kaam kori',  # 46
    'log kaam',  # 43
    'mein khada',  # 43
    'the tank',  # 43
    'worker is',  # 43
    'load ke',  # 42
    'farm',  # 40
    'tank farm',  # 40
    'basket',  # 40
    'uske',  # 38
    'the rig',  # 37
    'roof pe',  # 37
    'path',  # 37
    'tank ke',  # 35
    'directly below',  # 35
    'floor pe',  # 34
    'welder',  # 34
    'hands',  # 34
    'working directly',  # 34
    'derrickman neeche',  # 33
    'pit ke',  # 32
    'working in',  # 32
    'front',  # 32
    'man',  # 31
    'helper was',  # 31
    'operator was',  # 31
    'the derrick',  # 31
    'manually',  # 31
    'operating',  # 31
    'kaam chal',  # 30
    'cleaning',  # 30
    'beech',  # 30
    'workers are',  # 30
    'area mein',  # 30
    'underneath the',  # 30
    'the monkey',  # 30
    'personnel are',  # 30
    'employees',  # 30
    'the mud',  # 29
    'log khade',  # 29
    'standing under',  # 29
    'helper kaam',  # 29
    'exposed',  # 29
    'next',  # 29
    'next to',  # 29
    'catwalk',  # 29
    'roustabout khade',  # 28
    'worker khada',  # 28
    'left hand',  # 28
    'floorhand',  # 28
    'in front',  # 28
    'public',  # 27
    'performing',  # 27
    'slinger',  # 27
    'party',  # 27
    'neeche derrickman',  # 27
    'compressor station',  # 27
    'positioned directly',  # 27
    'kaxot',  # 27
    'pass',  # 26
    'worker was',  # 25
    'top of',  # 25
    'pinch',  # 25
    'enter',  # 24
    'attempting',  # 24
    'helper bina',  # 23
    'paidal',  # 23
    'labour paidal',  # 23
    'the suspended',  # 23
    'upar khada',  # 23
    'dekh',  # 23
    'towards',  # 23
    'talot',  # 23
    'employee was',  # 23
    'house ke',  # 22
    'ke beech',  # 22
    'inside tank',  # 22
    'nh-37',  # 22
    'khada roustabout',  # 22
    'gol',  # 22
    'manuh ase',  # 22
    'contractor team',  # 22
    'within',  # 22
    'pinch point',  # 22
    's right',  # 22
    'contractor party',  # 21
    'standing inside',  # 21
    'well head',  # 21
    'manhole',  # 21
    'standing nearby',  # 21
    'touch',  # 21
    'lineman',  # 21
    'mein khade',  # 21
    'security guard',  # 21
    'daal',  # 21
    'khada helper',  # 21
    'on top',  # 21
    'attempting to',  # 21
    'helper ko',  # 20
    'close to',  # 20
    'paidal chal',  # 20
    'entered the',  # 20
    'attendant',  # 20
    'entering',  # 20
    'is working',  # 20
    'majot',  # 20
    'working near',  # 20
    'placing',  # 20
    'niche khada',  # 19
    'jaa',  # 19
    'welding kar',  # 19
    'roustabout neeche',  # 19
    'floor par',  # 19
    'chadh',  # 19
    'dekh raha',  # 19
    'tolot',  # 19
    'assistant',  # 19
    'against',  # 19
    'separator area',  # 19
    's left',  # 19
    'electrician',  # 18
    'paas kaam',  # 18
    'mistri kaam',  # 18
    'chala gaya',  # 18
    'standing underneath',  # 18
    'rasta',  # 18
    'derrick floor',  # 18
    'in line',  # 18
    'landing',  # 18
    'currently',  # 18
    'are working',  # 18
    'right hand',  # 18
    'positioned on',  # 18
    'worker neeche',  # 18
    'hath',  # 17
    'helper khade',  # 17
    'mein kaam',  # 17
    'roustabout bina',  # 17
    'ghus',  # 17
    'board par',  # 17
    'across',  # 17
    'ke khada',  # 17
    'cross',  # 17
    'is standing',  # 17
    'rakh',  # 17
    'neeche workers',  # 17
    'the head',  # 17
    'exposing',  # 17
    'crew is',  # 17
    'ke pass',  # 17
    'his hand',  # 17
    'bhitorot ase',  # 17
    'thakise',  # 17
    'exposure',  # 16
    'ke kaam',  # 16
    'derrickman khada',  # 16
    'climb',  # 16
    'etp',  # 16
    'kinare',  # 16
    'worker bina',  # 16
    'a worker',  # 16
    'behind',  # 16
    'roustabouts',  # 16
    'plinth',  # 16
    'holding',  # 16
    'stepped',  # 16
    'beech mein',  # 16
    'standing between',  # 16
    'fire-ot',  # 16
    'of fire-ot',  # 16
    'haat',  # 16
    'niche kaam',  # 16
    'rod basket',  # 16
    'hitting',  # 15
    'par kaam',  # 15
    'derrick man',  # 15
    'pe helper',  # 15
    'night',  # 15
    'people',  # 15
    'the well',  # 15
    'bagal',  # 15
    'pipe ke',  # 15
    'restricted',  # 15
    'adjacent',  # 15
    'touch kar',  # 15
    'bilkul',  # 15
    'observed',  # 15
    'beneath',  # 15
    'frame',  # 15
    'manuh kaam',  # 15
    'worker-e',  # 15
    'placing his',  # 15
    'struck employee',  # 15
    'an employee',  # 15
    'uske neeche',  # 14
    'crossing',  # 14
    'banksman',  # 14
    'road ke',  # 14
    'ke kinare',  # 14
    'pit mein',  # 14
    'pe roustabout',  # 14
    'towards the',  # 14
    'well plinth',  # 14
    'neeche labour',  # 14
    'approaching',  # 14
    'was struck',  # 14
    'reaching',  # 14
    'proximity',  # 14
    'bhitorot gol',  # 14
    'employee in',  # 14
    'neeche crew',  # 14
    'ek worker',  # 13
    'roof par',  # 13
    'pe khada',  # 13
    'andar kaam',  # 13
    'road pe',  # 13
    'utar',  # 13
    'climbing the',  # 13
    'helper ke',  # 13
    'the area',  # 13
    'member',  # 13
    'thaka',  # 13
    'close proximity',  # 13
    'v-door',  # 13
    'samne',  # 13
    'crew kaam',  # 13
    'working under',  # 12
    'stood',  # 12
    'farm mein',  # 12
    'neeche mistri',  # 12
    'peeche',  # 12
    'kinare labour',  # 12
    'baitha',  # 12
    'climbed',  # 12
    'too close',  # 12
    'aas',  # 12
    'aas paas',  # 12
    'check kar',  # 12
    'neeche worker',  # 12
    'derrick ke',  # 12
    'operator is',  # 12
    'uporot',  # 12
    'kaam cholise',  # 12
    'mechanic',  # 12
    'worker kaam',  # 12
    'workers khade',  # 12
    'entering the',  # 12
    'ggs-2',  # 12
    'fire-ot ase',  # 12
    'front of',  # 12
    'hand is',  # 12
    'hand was',  # 12
    'worker line',  # 12
    'within the',  # 12
    'the rod',  # 12
    'se nikal',  # 11
    'labourer',  # 11
    'area me',  # 11
    'khade roustabout',  # 11
    'jaa raha',  # 11
    'haath se',  # 11
    'rigger neeche',  # 11
    'pe kaam',  # 11
    'nh-37 road',  # 11
    'road par',  # 11
    'truck ke',  # 11
    'working below',  # 11
    'drill floor',  # 11
    'night shift',  # 11
    'was working',  # 11
    'bhitorot kaam',  # 11
    'chadh raha',  # 11
    'taraf',  # 11
    'ki taraf',  # 11
    'aage',  # 11
    'uske paas',  # 11
    'cross kar',  # 11
    'the wellhead',  # 11
    'gaon',  # 11
    'gaon ke',  # 11
    'ek roustabout',  # 11
    'workshop',  # 11
    'workshop area',  # 11
    'ot ase',  # 11
    'the potential',  # 11
    'hoi',  # 11
    'placed his',  # 11
    'hit the',  # 11
    'left leg',  # 11
    'danger',  # 11
    'his hands',  # 11
    'par khada',  # 10
    'roustabout ke',  # 10
    'wale',  # 10
    'tank mein',  # 10
    'blind spot',  # 10
    'helpers',  # 10
    'are standing',  # 10
]

# release_cue: 194 terms mined from the corpus
RELEASE_CUE_TERMS = [
    'fell',  # 762
    'released',  # 443
    'suddenly',  # 426
    'suddenly released',  # 412
    'release ह',  # 409
    'नक release',  # 408
    'slip',  # 372
    'slipped',  # 286
    'struck',  # 270
    'slip hua',  # 266
    'swung',  # 262
    'trip',  # 258
    'minor',  # 256
    'trip hua',  # 254
    'blew',  # 235
    'gir',  # 228
    'violently',  # 219
    'swung violently',  # 217
    'gir gaya',  # 204
    'spark',  # 203
    'blew back',  # 193
    'caught',  # 179
    'gira',  # 174
    'cut',  # 153
    'halka',  # 141
    'fisla',  # 141
    'batten',  # 140
    'wooden batten',  # 140
    'batten fisla',  # 140
    'paper',  # 140
    'halka paper',  # 140
    'paper cut',  # 140
    'cut laga',  # 140
    'scratch',  # 131
    'minor scratch',  # 131
    'scratch hua',  # 131
    'neeche gira',  # 130
    'chhitak',  # 130
    'paani',  # 129
    'paani chhitak',  # 129
    'chhitak gaya',  # 129
    'spark hua',  # 125
    'chhota',  # 123
    'chhota spark',  # 123
    'bench',  # 119
    'bench se',  # 119
    'minor trip',  # 118
    'dropped',  # 111
    'tripped',  # 97
    'incident',  # 69
    'ignited',  # 55
    'broke',  # 54
    'and fell',  # 54
    'failed',  # 50
    'came',  # 50
    'slip ho',  # 49
    'contacted',  # 47
    'tiny',  # 46
    'tiny spark',  # 46
    'explosion',  # 46
    'pair',  # 44
    'slipped and',  # 40
    'exploded',  # 37
    'porise',  # 35
    'pulled',  # 35
    'hol',  # 35
    'slid',  # 33
    'pinched',  # 33
    'collapsed',  # 32
    'fislai',  # 31
    'fislai porise',  # 31
    'contact',  # 30
    'rolled',  # 30
    'and struck',  # 30
    'became',  # 28
    'flash fire',  # 28
    'र समतल',  # 28
    'heavy shackle',  # 28
    'shackle drop',  # 28
    'drop hol',  # 28
    'parted',  # 27
    'got',  # 25
    'swing kar',  # 24
    'fell from',  # 24
    'causing',  # 24
    'ulajh',  # 23
    'ulajh gaya',  # 23
    'fell to',  # 23
    'pair ulajh',  # 22
    'was caught',  # 21
    'slipped on',  # 21
    'fell off',  # 20
    'caught in',  # 20
    'fisl',  # 19
    'pair fisl',  # 19
    'fisl gaya',  # 19
    'giraya',  # 18
    'struck by',  # 18
    'burst',  # 17
    'fire occurred',  # 17
    'lost',  # 16
    'slip kar',  # 16
    'free',  # 16
    'sprayed',  # 15
    'impact',  # 15
    'blew out',  # 14
    'ran',  # 14
    'fell on',  # 14
    'dislodged',  # 14
    'came down',  # 14
    'explosion occurred',  # 14
    'ruptured',  # 13
    'collided',  # 13
    'caught fire',  # 13
    'got caught',  # 13
    'shifted',  # 12
    'release hua',  # 12
    'snapped',  # 12
    'blew off',  # 12
    'worker slip',  # 12
    'tipped',  # 12
    'run',  # 12
    'forward',  # 12
    'pulled into',  # 12
    'swing hua',  # 11
    'causing a',  # 11
    'fell down',  # 11
    'slipped off',  # 11
    'backward',  # 11
    'activated',  # 11
    'pinched between',  # 11
    'caused',  # 10
    'die swung',  # 10
    'swung hua',  # 10
    'rolled over',  # 10
    'blown',  # 10
    'slid down',  # 10
    'apart',  # 10
    'came loose',  # 10
    'entangled',  # 10
    'fell onto',  # 9
    'crashed',  # 9
    'detached',  # 9
    'fell into',  # 9
    'disconnected',  # 9
    'tipped over',  # 9
    'made',  # 9
    'releasing',  # 9
    'rotated',  # 9
    'unexpectedly',  # 8
    'slip karke',  # 8
    'and hit',  # 8
    'and strike',  # 8
    'made contact',  # 8
    'became caught',  # 8
    'fallen',  # 8
    'fell backward',  # 8
    'almost knocked',  # 7
    'shocked',  # 7
    'boom swing',  # 7
    'gira diya',  # 7
    'loose ho',  # 7
    'swing ho',  # 7
    'backwards',  # 7
    'shot',  # 7
    'separated',  # 7
    'broke and',  # 7
    'rolled off',  # 7
    'ran over',  # 7
    'spun',  # 7
    'toward',  # 7
    'fell through',  # 7
    'into contact',  # 7
    'flipped',  # 7
    'began',  # 7
    'onto his',  # 7
    'drop ho',  # 6
    'jhatka',  # 6
    'pe gira',  # 6
    'load gir',  # 6
    'swing kiya',  # 6
    'lost control',  # 6
    'टकर',  # 6
    'accidentally',  # 6
    'switched on',  # 6
    'dropping',  # 6
    'causing the',  # 6
    'turned',  # 6
    'come',  # 6
    'broke off',  # 6
    'his foot',  # 6
    'fell over',  # 6
    'erupted',  # 6
    'struck his',  # 6
]

# no_release_cue: 23 terms mined from the corpus
NO_RELEASE_CUE_TERMS = [
    'release',  # 834
    'release nahi',  # 548
    'koi release',  # 544
    'nohoi',  # 289
    'release nohoi',  # 281
    'kunu',  # 275
    'kunu release',  # 273
    'abhi',  # 136
    'tak',  # 114
    'abhi tak',  # 114
    'tak koi',  # 42
    'about',  # 38
    'about to',  # 38
    'yet',  # 28
    'tak nahi',  # 23
    'not yet',  # 22
    'nahi gira',  # 20
    'fall occurred',  # 18
    'gira nahi',  # 9
    'yet dropped',  # 8
    'incident nahi',  # 6
    'tak gira',  # 6
    'shock nahi',  # 6
]

# outcome_cue: 228 terms mined from the corpus
OUTCOME_CUE_TERMS = [
    'chot',  # 975
    'chot nahi',  # 949
    'koi chot',  # 931
    'injury',  # 720
    'no injury',  # 588
    'occurred',  # 514
    'injury occurred',  # 503
    'aayi',  # 377
    'nahi aayi',  # 372
    'first',  # 201
    'fracture',  # 190
    'aid',  # 180
    'first aid',  # 178
    'lagi',  # 173
    'nahi lagi',  # 164
    'aid only',  # 140
    'fractured',  # 133
    'hazard',  # 130
    'koi hazard',  # 129
    'hazard nahi',  # 129
    'killed',  # 129
    'nuksan',  # 119
    'koi nuksan',  # 119
    'nuksan nahi',  # 119
    'died',  # 116
    'amputation',  # 114
    'burns',  # 112
    'injuries',  # 110
    'one',  # 103
    'hospitalized',  # 103
    'fracturing',  # 101
    'damage',  # 92
    'injured',  # 84
    'amputated',  # 78
    'broken',  # 77
    'arm',  # 71
    'fingertip',  # 65
    'fractures',  # 60
    'fatal',  # 50
    'fracturing his',  # 41
    'wrist',  # 40
    'amputation of',  # 37
    'no injuries',  # 36
    'middle',  # 35
    'serious',  # 32
    'fractured arm',  # 32
    'tibia',  # 31
    'no one',  # 30
    'one was',  # 30
    'fatality',  # 30
    'burns to',  # 30
    'was amputated',  # 29
    'dead',  # 28
    'ribs',  # 28
    'index',  # 27
    'fractures to',  # 27
    'electrocuted',  # 26
    'injury nahi',  # 25
    'was injured',  # 24
    'degree burns',  # 24
    'fatally',  # 24
    'hip',  # 24
    'hospital',  # 22
    'hospitalized with',  # 22
    'sustained',  # 21
    'fractured wrist',  # 21
    'partial',  # 21
    'amputation to',  # 21
    'ankle',  # 20
    'koi injury',  # 20
    'the left',  # 20
    'burned',  # 20
    'killing',  # 20
    'surgery',  # 20
    'femur',  # 20
    'laceration',  # 19
    'fingertip was',  # 19
    'second',  # 18
    'ko chot',  # 18
    'fibula',  # 18
    'passed',  # 18
    'breaking',  # 18
    'skull',  # 18
    'was hospitalized',  # 18
    'passed away',  # 17
    'multiple',  # 17
    'the right',  # 17
    'middle finger',  # 17
    'right leg',  # 16
    'both',  # 16
    'burn',  # 15
    'death',  # 15
    'pelvis',  # 15
    'severe',  # 15
    'fracture to',  # 15
    'fatally injured',  # 15
    'partial amputation',  # 15
    'hospitalization',  # 15
    'fractured his',  # 14
    'reported',  # 14
    'bone',  # 14
    'was killed',  # 14
    'pronounced',  # 14
    'pronounced dead',  # 14
    'second-degree',  # 14
    'second-degree burns',  # 14
    'right arm',  # 14
    'amputating',  # 14
    'the first',  # 14
    'serious injury',  # 13
    'kisi ko',  # 13
    'his leg',  # 13
    'tibia and',  # 13
    'forearm',  # 13
    'fatal injury',  # 13
    'killing him',  # 13
    'third-degree',  # 13
    'bones',  # 13
    'fingertip amputation',  # 13
    'required surgery',  # 13
    'fracture ho',  # 12
    'resulting',  # 12
    'resulting in',  # 12
    'crushing',  # 12
    'third-degree burns',  # 12
    'neck',  # 12
    'third',  # 12
    'third degree',  # 12
    'face and',  # 12
    'and fibula',  # 12
    'broken ribs',  # 12
    'amputations',  # 12
    'the fingertip',  # 12
    'fracturing the',  # 11
    'fatal injuries',  # 11
    'that required',  # 11
    'knuckle',  # 11
    'bruise',  # 10
    'minor cut',  # 10
    'rib',  # 10
    'shoulder',  # 10
    'hospitalized for',  # 10
    'fracturing her',  # 10
    'arm and',  # 10
    'second and',  # 10
    'and third',  # 10
    'concussion',  # 10
    'the finger',  # 10
    'the face',  # 10
    'chot lagi',  # 9
    'his injuries',  # 9
    'no personnel',  # 9
    'compound',  # 9
    'tip of',  # 9
    'ribs and',  # 9
    'required hospitalization',  # 9
    'finger amputation',  # 9
    'second degree',  # 8
    'minor bruise',  # 8
    'sustained a',  # 8
    'were amputated',  # 8
    'aid diya',  # 8
    'several',  # 8
    'fracture of',  # 8
    'knee',  # 8
    'head injuries',  # 8
    'head injury',  # 8
    'fatalities',  # 8
    'breaking his',  # 8
    'second-',  # 8
    'second- and',  # 8
    'and third-degree',  # 8
    'their right',  # 8
    'leg fracture',  # 8
    'fracturing it',  # 8
    'left arm',  # 8
    'lacerated',  # 8
    'the tip',  # 8
    'broken bones',  # 8
    'his ankle',  # 7
    'a fractured',  # 7
    'fingers were',  # 7
    'injury reported',  # 7
    'his wrist',  # 7
    'to hospital',  # 7
    'requiring',  # 7
    'the tibia',  # 7
    'pua',  # 7
    'kunu chot',  # 7
    'chot pua',  # 7
    'pua nai',  # 7
    'unconscious',  # 7
    'seriously',  # 7
    'chest',  # 7
    'severing',  # 7
    'injury to',  # 7
    'consciousness',  # 7
    'lower leg',  # 7
    'toes',  # 7
    'index fingertip',  # 7
    'skull fracture',  # 7
    'the thumb',  # 7
    'bleeding',  # 7
    'first knuckle',  # 7
    'ring fingertip',  # 7
    'the middle',  # 7
    'fingertips',  # 7
    'and required',  # 7
    'hospitalized and',  # 7
    'fractured tibia',  # 6
    'a fracture',  # 6
    'the hospital',  # 6
    'fatal head',  # 6
    'seriously injured',  # 6
    'later',  # 6
    'his skull',  # 6
    'elbow',  # 6
    'hand and',  # 6
    'compound fracture',  # 6
    'fractured hip',  # 6
    'spleen',  # 6
    'serious burns',  # 6
    'broke his',  # 6
    'laceration to',  # 6
    'crushed and',  # 6
    'amputating the',  # 6
    'amputated the',  # 6
    'and middle',  # 6
]

# pseudo_control: 15 terms mined from the corpus
PSEUDO_CONTROL_TERMS = [
    'harness pehna',  # 32
    'helmet',  # 30
    'hard hat',  # 25
    'pehne',  # 16
    'full body',  # 16
    'body harness',  # 16
    'pehna hua',  # 14
    'wearing full',  # 10
    'a hard',  # 10
    'ppe pehna',  # 8
    'pehna hai',  # 8
    'पहन ह',  # 7
    'cones',  # 7
    'scba pehna',  # 6
    'pehne hue',  # 6
]


def _alt(terms: list[str]) -> str:
    """Longest-first alternation so "gas test" wins over "gas"."""
    esc = sorted((re.escape(t) for t in terms), key=len, reverse=True)
    return r"\b(?:" + "|".join(esc) + r")\b" if esc else r"(?!)"


MINED = {
    'energy_cue': re.compile(_alt(ENERGY_CUE_TERMS), re.I),
    'control_absent': re.compile(_alt(CONTROL_ABSENT_TERMS), re.I),
    'control_present': re.compile(_alt(CONTROL_PRESENT_TERMS), re.I),
    'control_ineffective': re.compile(_alt(CONTROL_INEFFECTIVE_TERMS), re.I),
    'exposure_cue': re.compile(_alt(EXPOSURE_CUE_TERMS), re.I),
    'release_cue': re.compile(_alt(RELEASE_CUE_TERMS), re.I),
    'no_release_cue': re.compile(_alt(NO_RELEASE_CUE_TERMS), re.I),
    'outcome_cue': re.compile(_alt(OUTCOME_CUE_TERMS), re.I),
    'pseudo_control': re.compile(_alt(PSEUDO_CONTROL_TERMS), re.I),
}
